### ISSUE TITLE
[Crash] abs(), π, e, unsupported in functions entered

### ISSUE THREAD

**Issue by makloooo** [jherr029/Graphing-Calculator#3]
I mentioned this to Tianyou, and he said he would let AJ know. Don't know what's going on, but I'll leave this here for record-keeping.

The app will crash upon entering any of the symbols in the function list. The cfg parser will accept them as a valid function, since they are valid math symbols, and will crash at the ExpressionEvaluator. Since they're just constants, I assume they will be converted as so somewhere in the back end. I'll let you guys handle it.

_How to reproduce_:
1. Create a valid function with abs(), π, or 'e' in it.

**Comment by jherr029** [comment]
abs has been removed from the keyboard

**Comment by makloooo** [comment]
abs no longer supported, π and e are supported now
